The know problems with this version are:
 1. ~/stalingrad/examples/run
    example
      Error: Arguments to plus do not conform
    triple
      Error: Arguments to plus do not conform
    hessian
      Error: Arguments to plus do not conform
 2. ~/stalingrad/examples/p-examples/run
      saddle-stalingrad1000
      particle-stalingrad1000
    exhibit three problems
    a. We attempt to union s914:(BUNDLE #T (PERTURBATION #T)) to
       s1358:(BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F))) but the
       former is not a member of the latter so the unioner m1358_914 doesn't
       exist. Ditto for m1358_913. Also, there is no widener from s913 or s914
       to s1358.
    b. (PERTURBATION (UNION #T #F)) is abstract-value=? to
       (UNION (PERTURBATION #T) (PERTURBATION #F)), i.e. that s310 has the
       same extension as s1198 but not the same intension.
    c. s1496:(PAIR () (UNION #T #F) (PERTURBATION (UNION #T #F))) is
       abstract-value=? to s1997:
       (PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
       but they don't have the same intension. bundle1997 exists but bundle1496
       does not.
-------------------------------------------------------------------------------
saddle-stalingrad1000.c: In function ‘bundle1997’:
saddle-stalingrad1000.c:25148: warning: implicit declaration of function ‘m1358_914’
saddle-stalingrad1000.c:25148: warning: implicit declaration of function ‘m1358_913’
saddle-stalingrad1000.c:25148: error: incompatible types in return
saddle-stalingrad1000.c:25148: warning: control reaches end of non-void function
saddle-stalingrad1000.c: In function ‘f3657’:
saddle-stalingrad1000.c:25406: warning: implicit declaration of function ‘bundle1496’
saddle-stalingrad1000.c:25406: error: incompatible type for argument 1 of ‘f3658’
saddle-stalingrad1000.c: In function ‘f3635’:
saddle-stalingrad1000.c:25407: error: incompatible type for argument 1 of ‘f3636’
saddle-stalingrad1000.c: In function ‘f3609’:
saddle-stalingrad1000.c:25408: error: incompatible type for argument 1 of ‘f3612’
saddle-stalingrad1000.c: In function ‘f3655’:
saddle-stalingrad1000.c:25516: error: incompatible type for argument 2 of ‘f3656’
saddle-stalingrad1000.c: In function ‘f3633’:
saddle-stalingrad1000.c:25517: error: incompatible type for argument 2 of ‘f3634’
saddle-stalingrad1000.c: In function ‘f3603’:
saddle-stalingrad1000.c:25518: error: incompatible type for argument 2 of ‘f3606’
-------------------------------------------------------------------------------
particle-stalingrad1000.c: In function ‘bundle2563’:
particle-stalingrad1000.c:32286: warning: implicit declaration of function ‘m1906_1048’
particle-stalingrad1000.c:32286: warning: implicit declaration of function ‘m1906_1046’
particle-stalingrad1000.c:32286: error: incompatible types in return
particle-stalingrad1000.c:32286: warning: control reaches end of non-void function
particle-stalingrad1000.c: In function ‘f3733’:
particle-stalingrad1000.c:32744: warning: implicit declaration of function ‘bundle2039’
particle-stalingrad1000.c:32744: error: incompatible type for argument 1 of ‘f3734’
particle-stalingrad1000.c: In function ‘f3731’:
particle-stalingrad1000.c:32965: error: incompatible type for argument 2 of ‘f3732’
-------------------------------------------------------------------------------
Ding
("m" 1358 "_" 914)
v:(PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
v1:(UNION #T #F)
v2:(UNION (PERTURBATION #T) (PERTURBATION #F))
u1:#T
(bundle u1 v2):(BUNDLE #T (PERTURBATION #T))
(bundle v1 v2):(BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
-------------------------------------------------------------------------------
Ding
("m" 1358 "_" 913)
v:(PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
v1:(UNION #T #F)
v2:(UNION (PERTURBATION #T) (PERTURBATION #F))
u1:#F
(bundle u1 v2):(BUNDLE #F (PERTURBATION #F))
(bundle v1 v2):(BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
-------------------------------------------------------------------------------
// (UNION #T #F)
struct s310{int t;};
// (PERTURBATION (UNION #T #F))
struct s920{struct s310 p;};
// (BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
struct s1358{struct s310 p;struct s920 t;};
// (PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
struct s1997{struct s310 a;struct s1198 d;};

// X:(PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
// result:(BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
static INLINE struct s1358 bundle1997(struct s1997 x)
{return x.a.t==0?
        // when (CAR X)=#T
        // union (BUNDLE #T (PERTURBATION #T)) which is correctly void
        // to (BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
        m1358_914():
        // when (CAR X)=#F
        // union (BUNDLE #F (PERTURBATION #F)) which is correctly void
        // to (BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F)))
        m1358_913();}

The issue is that we attempt to union s914:(BUNDLE #T (PERTURBATION #T)) to
s1358:(BUNDLE (UNION #T #F) (PERTURBATION (UNION #T #F))) but the former is
not a member of the latter so the unioner m1358_914 doesn't exist. Ditto for
m1358_913. Also, there is no widener from s913 or s914 to s1358.
-------------------------------------------------------------------------------
// (UNION #T #F)
struct s310{int t;};
// (PERTURBATION (UNION #T #F))
struct s920{struct s310 p;};
// (PAIR () (UNION #T #F) (PERTURBATION (UNION #T #F)))
struct s1496{struct s310 a;struct s920 d;};
// probably (UNION (PERTURBATION #T) (PERTURBATION #F))
struct s1198{int t;};
// (PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
struct s1997{struct s310 a;struct s1198 d;};


// bundle1496 isn't declared/defined
// s1496:(PAIR () (UNION #T #F) (PERTURBATION (UNION #T #F)))
// s1997:(PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
static INLINE struct s1358 f3657(struct s1496 x)
{struct s1496 x2444=x;return f3658(bundle1496(x2444));}
static INLINE struct s1358 f3635(struct s1496 x)
{struct s1496 x2444=x;return f3636(bundle1496(x2444));}
static INLINE struct s1358 f3609(struct s1496 x)
{struct s1496 x2444=x;return f3612(bundle1496(x2444));}

The issue is that s1496:(PAIR () (UNION #T #F) (PERTURBATION (UNION #T #F)))
is abstract-value=? to
s1997:(PAIR () (UNION #T #F) (UNION (PERTURBATION #T) (PERTURBATION #F)))
but they don't have the same intension. bundle1997 exists but bundle1496 does
not.

// (UNION #T #F)
struct s310{int t;};
// (PERTURBATION (UNION #T #F))
struct s920{struct s310 p;};
// probably (UNION (PERTURBATION #T) (PERTURBATION #F))
struct s1198{int t;};

// perturb310 returns s1198 but f3656, f3634, and f3606 take s920 as the
// second argument
static INLINE struct s1358 f3655(struct s984 c,struct s310 x)
{struct s310 x2446=x;return f3656(m983(c.x2450),perturb310(x2446));}
static INLINE struct s1358 f3633(struct s993 c,struct s310 x)
{struct s310 x2446=x;return f3634(m992(c.x2450),perturb310(x2446));}
static INLINE struct s1358 f3603(struct s1002 c,struct s310 x)
{struct s310 x2446=x;return f3606(m1001(c.x2450),perturb310(x2446));}

The issue is that (PERTURBATION (UNION #T #F)) is abstract-value=? to
(UNION (PERTURBATION #T) (PERTURBATION #F)), i.e. that s310 has the same
extension as s1198 but not the same intension.